### ISSUE TITLE
`pull_request` and `pull_request_review` have independent check status

### ISSUE THREAD

**Issue by SnowCait** [snow-actions/unanimously-approved#49]
Last user approve:
❌ `unanimously-approved (pull_request)` (outdated)
✔️  `unanimously-approved (pull_request_review)`
![image](https://user-images.githubusercontent.com/1297512/155320857-e5f1734a-da36-468f-b5c9-6c83d56b7b6d.png)

This prevents merge.
Outdated check status should disappear.

**Comment by SnowCait** [comment]
This doesn't prevent merge, but outdated check status should disappear.

**Comment by SnowCait** [comment]
Create a new check status which reflect conclusion.
Let `unanimously-approved` always success.

**Comment by genebean** [comment]
I am just now trying this action out and have run into this. Rerunning a check causes it to pass, but this is less than ideal

**Comment by SnowCait** [comment]
Release [v2.0.0](https://github.com/snow-actions/unanimously-approved/discussions/68).

@genebean
Try it.
